name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    uses: contact-api/.github/.github/workflows/test.yml@v1.0.1

  publish:
    needs: test
    uses: contact-api/.github/.github/workflows/publish.yml@v1.0.1
    secrets: inherit
